CREATE USER learner_ro WITH PASSWORD 'learner';
GRANT CONNECT ON DATABASE healthcare TO learner_ro;
GRANT USAGE ON SCHEMA public TO learner_ro;
GRANT SELECT ON ALL TABLES IN SCHEMA public TO learner_ro;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT ON TABLES TO learner_ro;
